// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  approach: dynamic(() => import("./Approach")),
  biography: dynamic(() => import("./Biography")),
  certifications: dynamic(() => import("./Certifications")),
  contact: dynamic(() => import("./Contact")),
  content_index: dynamic(() => import("./ContentIndex")),
  cta: dynamic(() => import("./Cta")),
  education: dynamic(() => import("./Education")),
  experience: dynamic(() => import("./Experience")),
  faq: dynamic(() => import("./Faq")),
  featured_projects: dynamic(() => import("./FeaturedProjects")),
  hero: dynamic(() => import("./Hero")),
  image_block: dynamic(() => import("./ImageBlock")),
  services: dynamic(() => import("./ServicesPage")),
  tech_list: dynamic(() => import("./TechList")),
  testimonial: dynamic(() => import("./Testimonial")),
  text_block: dynamic(() => import("./TextBlock")),
};
